# Generated by Django 3.2.15 on 2022-10-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
