# Generated by Django 3.2.15 on 2022-10-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20221013_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='in progress', max_length=20),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='data/'),
        ),
    ]
