# Generated by Django 3.2.15 on 2022-10-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20221025_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='price',
        ),
        migrations.AddField(
            model_name='user',
            name='tariff',
            field=models.BooleanField(default=False),
        ),
    ]
