# Generated by Django 3.2.15 on 2022-10-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20221027_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tariff',
            field=models.BooleanField(default=True),
        ),
    ]
